### PR TITLE
[Backport Foxy] Included improvements to increase code coverage

### PR DESCRIPTION
**Pull request by ahcorde**
This PR depends on: 
  - https://github.com/ros2/rcpputils/pull/103

Included error checks, return the right code errors, avoid crashes, etc

### CODE REVIEW

**Review by brawner — APPROVED** [review]
Can you update the title and description, this PR just seems like bug fixes for `rmw_node.cpp` and does not actually affect code coverage much.

**Comment by ahcorde** [comment]
@ros-pull-request-builder retest this please

**Comment by ahcorde** [comment]
Building `up-to` rmw_cyclonedds_cpp` and testing `rmw_cyclonedds_cpp`:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12736/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7697/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10450/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12683/)

**Comment by ahcorde** [comment]
There is an open issue https://github.com/ros2/ros2/issues/942 about the cppcheck failure in the Github Actions 

```
  [5.800s] 2: [src/rmw_node.cpp:705]: (error: unknownMacro) There is an unknown macro here somewhere. Configuration is required. If RCUTILS_STRINGIFY is a macro then please configure it.
```
`"rcutils/macros.h"` is included in the rmw_node.cpp file.

ROS 2 buildfarm is fine, @ivanpauno or @eboasson any thoughts ?

**Comment by ivanpauno** [comment]
Apply [this patch](https://github.com/ros2/rmw_cyclonedds/pull/237) to the Foxy branch.
There are other possible solutions as discussed [here](https://github.com/ros2/rmw_cyclonedds/issues/220), but I would apply the same patch that was used on master.

**Pull request merged**
