### PR TITLE
rmw_cyclonedds_cpp/CMakeLists.txt: add -latomic for RISC-V

### PR DESCRIPTION
**Pull request by guillaume-pais-siemens**
Co-authored-by: Ivan Santiago Paunovic <ivanpauno@ekumenlabs.com>

See Pull Request: add -latomic in CMakelist.txt #327

### CODE REVIEW

**Comment by ivanpauno** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15134/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9863/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12818/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15304/)

**Review by ivanpauno — APPROVED** [review]

**Review by eboasson — APPROVED** [review]
LGTM too!

**Comment by ivanpauno** [comment]
Thanks @guillaume-pais-siemens !!

**Comment by ivanpauno** [comment]
@mergifyio backport foxy galactic

**Pull request merged**
