### PR TITLE
update signature for added pub/sub options

### PR DESCRIPTION
**Pull request by eboasson**
This relates to https://github.com/ros2/rmw/pull/187.

Before merging, it'd probably be best to make a "dashing" branch.

Signed-off-by: Erik Boasson <eb@ilities.com>

### CODE REVIEW

**Comment by dirk-thomas** [comment]
I would suggest holding off on branch and get https://github.com/ros2/rmw/issues/188#issuecomment-540058781 resolved first. Than you should be easily able to keep supporting both ROS distros from the same branch.

**Comment by rotu** [comment]
I wasn't able to find a solution with SFINAE to make it cross-compatible, but I think I found a decent enough alternative:

https://github.com/eboasson/rmw_cyclonedds/pull/1

**Comment by rotu** [comment]
I figured out how to do this cleanly with SFINAE! I prefer this approach, but I'll leave you guys to choose.

https://github.com/eboasson/rmw_cyclonedds/pull/2

A few tricks:
1. The `extern "C"` linkage specifier only needs to be on the function *declaration* in the `rmw.h` header and will link the matching overload.
2. I had to declare the new types (e.g. `rmw_subscription_options_t`) to be template parameters, so that they don't trigger an unknown type name.
3. Where I used new properties of existing classes, I had to replace the class name (e.g. `rmw_subscription_t`) with a template argument so it views it as a *substitution failure* instead of a *missing member*.

**Comment by rotu** [comment]
Good to know. What’s the failure on MacOS?

**Comment by eboasson** [comment]
Closing because #51 sorted it out

**Pull request closed without merging**
