### PR TITLE
implement safer align function

### PR DESCRIPTION
**Pull request by dodsonmg**
avoids unnecessary casts to pointer and pointer manipulation by reference.

this is the same as PR #141, which was previously merged into `master`, but way ahead of the `dashing-eloquent` fork.

### CODE REVIEW

**Comment by dodsonmg** [comment]
Looks like Windows test failed while acquiring dependencies...

**Comment by rotu** [comment]
@dodsonmg No need. I need to backport https://github.com/ros2/rmw_cyclonedds/pull/181 which uses setup-ros@master to fix this bug: https://github.com/ros-tooling/setup-ros/issues/156

@thomas-moulard time to cut a new release or recommend people use master? https://github.com/ros-tooling/setup-ros/blob/master/README.md#usage

**Comment by dodsonmg** [comment]
For my own planning purposes:  are you waiting for the Windows CI to be fixed before merging (same question for #189)?

**Comment by rotu** [comment]
> For my own planning purposes: are you waiting for the Windows CI to be fixed before considering the merge (same question for #189)?

Sorry, please don't wait on me. I'm taking a break from Cyclone stuff (indefinite but hopefully not long). I defer to @eboasson.

**Comment by eboasson** [comment]
@dodsonmg any reason this isn't a cherry-pick? It looks to me like the change is identical, and keeping the metadata intact would be better.

I don't think there is a need to wait for the windows build failure in the CI to be addressed given that the changes are fine on Foxy and don't interact with the ROS libraries. But if, e.g., @nuclearsandwich or @jacobperron says differently, then it is different.

**Comment by dodsonmg** [comment]
Sure.  I just don't know how to do it.

**Comment by dodsonmg** [comment]
Cherry picking seems to have worked.  Windows build still fails, and for some reason the MacOS build was cancelled...  I can push again to see if I can dislodge the MacOS build?

**Comment by dodsonmg** [comment]
Any other feedback on this one (i.e., advice for getting through the cancelled builds)?

Same for #189.

**Comment by eboasson** [comment]
@dodsonmg no further feedback other than thanks. Given the nature of changes, the fact that the build failures here are unrelated and that it works fine on Foxy, I am good with merging it. The delay is just the result of having too much to do ...

**Pull request merged**
