### PR TITLE
Update graph API return codes.

### PR DESCRIPTION
**Pull request by hidmic**
Connected to https://github.com/ros2/rmw/pull/272. This patch affects:
- `rmw_get_node_names()`
- `rmw_get_node_names_with_enclaves()`
- `rmw_get_topic_names_and_types()`
- `rmw_get_service_names_and_types()`
- `rmw_get_publishers_info_by_topic()`
- `rmw_get_subscriptions_info_by_topic()`
- `rmw_get_subscriber_names_and_types_by_node()`
- `rmw_get_publisher_names_and_types_by_node()`
- `rmw_get_service_names_and_types_by_node()`
- `rmw_get_client_names_and_types_by_node()`
- `rmw_count_publishers()`
- `rmw_count_subscribers()`

### CODE REVIEW

**Review by eboasson — APPROVED** [review]
LGTM, thanks for going over all the argument checking and return values with such care!

**Review by Lobotuerk — APPROVED** [review]
LGTM

**Comment by hidmic** [comment]
CI up to `test_rmw_implementation`:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12375/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7344/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10087/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12287/)

**Comment by jacobperron** [comment]
@hidmic I suggest testing additional packages above `test_rmw_implementation`. E.g. https://github.com/ros2/rmw_cyclonedds/pull/241 seems to have introduced test regressions several other packages further downstream.

**Comment by hidmic** [comment]
@jacobperron I believe the problem with #241 was that CI was not properly run against actual tests (see [here](https://ci.ros2.org/job/ci_linux/12301/)). Every modification here is checked against a corresponding test.

**Comment by hidmic** [comment]
CI up to `test_rmw_implementation`, `rcl`, and `rclcpp`:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12388/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7356/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10099/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12300/)

**Comment by hidmic** [comment]
Argh, I had to rebase after #245.

---

CI up to `test_rmw_implementation`, `rcl`, and `rclcpp`:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12390/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7358/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10101/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12303/)

**Comment by hidmic** [comment]
Alright, going in! Thanks for all the good reviews!

**Pull request merged**
