### PR TITLE
rmw_destroy_node must remove node from graph cache

### LINKED ISSUE #211: failing test checking node names
This nightly test is failing for CycloneDDS: http://build.ros2.org/view/Rci/job/Rci__nightly-cyclonedds_ubuntu_focal_amd64/29/testReport/rclcpp_lifecycle/TestDefaultStateMachine/test_graph/

Each test in the gtest creates a node with the name `/testnode`. But when it goes out of scope (which results in calling `rmw_destroy_node`) the metadata about the node isn't being removed. As a result the specific failing test reports 23 nodes (all with the same node).

The function never calls `common->graph_cache.remove_node()`. On the contrary - it even adds the node another time during the destruction: https://github.com/ros2/rmw_cyclonedds/blob/4383911781047513545bc61092150d3ca080fdab/rmw_cyclonedds_cpp/src/rmw_node.cpp#L1335

Inserting two calls below the `rmw_publish()` call within `rmw_destroy_node()` makes the test pass but I am not sure if that is the right way to address the problem.

<details>

<summary>Potential patch:</summary>

```
iff --git a/rmw_cyclonedds_cpp/src/rmw_node.cpp b/rmw_cyclonedds_cpp/src/rmw_node.cpp
index 53ca3c4..279ac57 100644
--- a/rmw_cyclonedds_cpp/src/rmw_node.cpp
+++ b/rmw_cyclonedds_cpp/src/rmw_node.cpp
@@ -1335,6 +1335,8 @@ extern "C" rmw_ret_t rmw_destroy_node(rmw_node_t * node)
       common->graph_cache.add_node(common->gid, node->name, node->namespace_);
     result_ret = rmw_publish(
       common->pub, static_cast<void *>(&participant_msg), nullptr);
+    static_cast<void>(common->graph_cache.remove_node(common->gid, node->name, node->namespace_));
+    static_cast<void>(common->graph_cache.remove_node(common->gid, node->name, node->namespace_));
   }
 
   rmw_context_t * context = node->context;
```

</details>

### PR DESCRIPTION
**Pull request by eboasson**
This fixes #211 by fixing an embarrassing copy-paste mistake.

### CODE REVIEW

**Comment by eboasson** [comment]
> 😮

Quite so!

**Comment by ivanpauno** [comment]
Ci for completeness, to see is the failure is fixed:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11640/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6769/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9525/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11622/)

**Comment by eboasson** [comment]
@ivanpauno sorry, I should've waited a bit ... I tried it locally, it makes perfect sense, it matches `rmw_fastrtps` and I did a CI run for rclcpp against my own branch early this morning https://ci.ros2.org/job/ci_linux/11638/testReport/rclcpp/ so I think we're good.

By the way: how do you do you get those CI results in a comment?

**Comment by eboasson** [comment]
Ah, of course! I actually thought you had some magic trick :)

Next time I'll try to include it in the PR.

**Comment by dirk-thomas** [comment]
> > how do you do you get those CI results in a comment?

> I always copy that from an old comment

Usually you trigger a build of the following Jenkins job with the desired parameter: https://ci.ros2.org/job/ci_launcher/

That job not only triggers the four platform/arch specific builds but also contains the markdown snippet with the four badges in the console output to copy-n-paste.

**Comment by dirk-thomas** [comment]
@eboasson Thanks for the quick fix!

**Comment by ivanpauno** [comment]
> Usually you trigger a build of the following Jenkins job with the desired parameter: https://ci.ros2.org/job/ci_launcher/
>
> That job not only triggers the four platform/arch specific builds but also contains the markdown snippet with the four badges in the console output to copy-n-paste.

I didn't know about that, that will make my life much easier :smiley: .

**Pull request merged**
