### PR TITLE
Fix build warnings

### PR DESCRIPTION
**Pull request by ivanpauno**
Fixes https://github.com/ros2/rmw_cyclonedds/pull/145#issuecomment-617996341.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10401/)

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The custom GitHub action is already failing on the target branch.

**Comment by ivanpauno** [comment]
Failures in Windows checks aren't related, merging!

**Comment by rotu** [comment]
Created https://github.com/eProsima/Fast-RTPS/issues/1173 as this seems to be in fastrtps

**Comment by eboasson** [comment]
Thanks @ivanpauno ☺️

**Pull request merged**
