### PR TITLE
Remove unused CMake extras

### PR DESCRIPTION
**Pull request by rotu**
Signed-off-by: Dan Rose <dan@digilabs.io>

### CODE REVIEW

**Comment by rotu** [comment]
@dirk-thomas could you please give me access to run a CI build myself? (Or else run it for me) Thanks!

**Comment by dirk-thomas** [comment]
Since this change is again on a fork (see https://github.com/ros2/rmw_cyclonedds/pull/80#issuecomment-564757216) I won't manually trigger a set of builds this time.

@nuclearsandwich Can you reach out to @rotu regarding permissions to trigger builds on ci.ros2.org?

**Comment by rotu** [comment]
Oof. I’m sorry about that. I totally meant to push to a fork in the repo :-/.

**Comment by dirk-thomas** [comment]
Feel free to push your branch from the fork to the upstream repo and I can trigger the CI builds.

**Comment by rotu** [comment]
Let's give this a shot...
<a href='https://ci.ros2.org/job/ci_linux/8946/'></a>

**Comment by eboasson** [comment]
@rotu did you have any reason for not merging this already? As far as I can tell, it does exactly what it says on the tin, the build's fine and it's been approved for quite some time. I'll happily press the merge button for you, if you prefer me to do it.

**Comment by rotu** [comment]
Oof! Nope. The only reason I hadn’t merged this is because I was trying to get comfortable running CI first

**Pull request merged**
