### PR TITLE
Clean up package xml dependencies

### PR DESCRIPTION
**Pull request by rotu**
There are some unnecessary dependencies and some missing runtime dependencies. This PR tames the mess

### CODE REVIEW

**Comment by cottsay** [comment]
This is far too aggressive.

Just look at the other RMWs. None of them are doing this: `find src -name package.xml | xargs grep rosidl_typesupport_introspection_c`

There is a balance to be struck here. I'm not saying that this `package.xml` doesn't need some love, but blindly converting all of the build dependencies into run dependencies is unacceptable.

**Comment by rotu** [comment]
It's agressive but it's not blind, and I think the changes are correct...

We *do* use `rosidl_typesupport_introspection_c` at runtime (`rosidl_typesupport_introspection_c__identifier`). I suspect the reason this code works today is because this and other packages are pulled in as a runtime dependency via `rosidl_default_runtime`.

I don't think we *have* any build dependencies that aren't used as runtime dependencies, but correct if wrong.

**Comment by cottsay** [comment]
> We do use rosidl_typesupport_introspection_c at runtime.

You're right. It's easy to prove, too:
```
$ ldd /opt/ros/eloquent/lib/librmw_cyclonedds_cpp.so | grep /opt/ros/eloquent | awk '{ print $1 }'
libddsc.so.0
librosidl_typesupport_introspection_c.so
librosidl_typesupport_introspection_cpp.so
librcutils.so
librmw.so
librosidl_generator_c.s
```

So I'm sold on:
- cyclonedds
- rcutils
- rmw
- rosidl_generator_c
- rosidl_typesupport_introspection_c
- rosidl_typesupport_introspection_cpp

How do you justify `cyclonedds_cmake_module`? Clearly that should remain `build_depend`/`build_export_depend`, no?

We should fix the other RMWs that are missing the dependencies as well.

> Since all dependencies were build_export_depend which essentially maps to a run dependency in a Debian package this change is a no-op from a packaging perspective.

There are 108 of such entries in the packages in `ros2.repos`. Does that statement apply to all of them? Why was the dependency type introduced if Debian packaging prevents us from using it?

**Comment by cottsay** [comment]
> Clearly that should remain build_depend/build_export_depend, no?

Actually, I'm not even convinced it should be a `build_export_depend`. It isn't mentioned in `ament_cmake_export_dependencies-extras.cmake`.

**Comment by rotu** [comment]
@cottsay, I think once CycloneDDS is found, the CMake module is no longer needed. Since `rmw_cyclonedds_cpp` can be loaded even dynamically at runtime (via Poco) after other packages are built, it *can't* really impose any transitive build dependencies.

**Comment by cottsay** [comment]
> it can't really impose any transitive build dependencies

So the `<build_depend>cyclonedds_cmake_module</build_depend>` is appropriate. Right?

**Comment by rotu** [comment]
Mayyybe? I'm not totally sure, and it certainly straddles the line.

I think `<Package>Config.cmake` would be a `build_depend` since it's supposed to be specialized to the compilation target but `Find<Package>.cmake` would be a `buildtool_depend`, since it is expected to run on the host system and does not need to be recompiled for different compilation targets.

**Comment by dirk-thomas** [comment]
> How do you justify cyclonedds_cmake_module?

`cyclonedds_cmake_module` needs to be an exported dependency because it provides the CMake module to find CycloneDDS.

> Why was the dependency type introduced if Debian packaging prevents us from using it?

The motivation and rational sections of [REP 140](https://ros.org/reps/rep-0140.html#motivation) are describing this.

**Comment by cottsay** [comment]
> `cyclonedds_cmake_module` needs to be an exported dependency because it provides the CMake module to find CycloneDDS.

Clearly you see something that I don't. I can find no implicit CMake dependency on `CycloneDDS` being exported:
```
$ grep CycloneDDS /opt/ros/eloquent/share/rmw_cyclonedds_cpp -R
/opt/ros/eloquent/share/rmw_cyclonedds_cpp/package.xml:  <description>Implement the ROS middleware interface using Eclipse CycloneDDS in C++.</description>
$
```

Please don't just tell me that it is needed @dirk-thomas, tell me why so that I know where to look next time. Is the problem that it SHOULD be exported, but isn't?

I do see that `/opt/ros/eloquent/include/rmw_cyclonedds_cpp/serdata.hpp` is referencing a header provided by `CycloneDDS` itself, and is relative to `/opt/ros/eloquent/include`, so is probably being found downstream despite not being `find_package()`'d.

**Comment by dirk-thomas** [comment]
> > `cyclonedds_cmake_module` needs to be an exported dependency because it provides the CMake module to find CycloneDDS.

> Clearly you see something that I don't. I can find no implicit CMake dependency on CycloneDDS being exported:

I based my comment on the understanding of how all other RMW impl. work. See e.g. for Connext:
https://github.com/ros2/rmw_connext/blob/c27c246b542d2980ed3fb039884cb34bc6dee8a6/rmw_connext_cpp/rmw_connext_cpp-extras.cmake#L15-L22

This CMake extra logic is necessary to indicate that while the RMW package is present the underlying vendor package is not and therefore you can't use the RMW package.

So yes, atm the export dependency is not necessary. But that CMake extra logic is missing for CycloneDDS and when it is added the export dependency is necessary.

**Comment by rotu** [comment]
We can add it if/when the export dependency becomes necessary. I'd prefer to get rid of the package altogether and add a config module to the Cyclone project.

**Pull request merged**
