### PR TITLE
WIP: Only use cpp typesupport

### PR DESCRIPTION
**Pull request by rotu**

### CODE REVIEW

**Comment by dirk-thomas** [comment]
With C typesupport removed do C messages (e.g. coming from rclpy) still work?

**Comment by rotu** [comment]
> With C typesupport removed do C messages (e.g. coming from rclpy) still work?

Why shouldn't they? The messages are the same on the wire, and the cpp introspection is just a thin layer on top of the c introspection. I thought the default generators *always* generate the cpp introspection?

**Comment by dirk-thomas** [comment]
But if Python publishes a message it hands an instance of a C message to the rmw API. In order to read / interpret that you need the corresponding C introspection typesupport.

**Comment by rotu** [comment]
Gotcha. Is this only local? Or does typesupport travel on the wire?

**Comment by dirk-thomas** [comment]
Typesupport provides information / functionality for a data type in a specific programming language (it could be introspection information, it could be a conversion function between the ROS type and an external type - usually the one from a DDS vendor). It never affects the wire representation of a message.

**Comment by rotu** [comment]
Gotcha. I figured the ROS2 runtime interpreted between different typesupports and the introspection typesupport was just a language-specific layer. I guess I have some reworking to do!

**Pull request closed without merging**
