### PR TITLE
Fix serialization on non-32-bit, big-endian systems

### PR DESCRIPTION
**Pull request by rotu**
Serialization issue reported in https://github.com/eclipse-cyclonedds/cyclonedds/issues/488

### CODE REVIEW

**Comment by rotu** [comment]
full CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10292/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5826/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8372/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10189/)

**Comment by dodsonmg** [comment]
You may not need the verification, but I applied the patch and it works on my system.  Here's the tcpdump for the packet associated with publishing `Hello, world! 53`.  The subscriber correctly receives and displays the string and count.

Thanks!

```
09:12:54.819030 IP 10.0.2.15.25958 > 0.0.0.0.15920: UDP, length 116
        0x0000:  4500 0090 0000 0000 8011 2e4f 0a00 020f  E..........O....
        0x0010:  0000 0000 6566 3e30 007c 0000 5254 5053  ....ef>0.|..RTPS
        0x0020:  0201 0110 0110 e0c7 69af d7a4 d887 fa49  ........i......I
        0x0030:  0900 0008 5e98 2196 d045 3deb 1504 0030  ....^.!..E=....0
        0x0040:  0000 0010 0000 0000 0000 1303 0000 0000  ................
        0x0050:  0000 0036 0000 0000 0000 0011 4865 6c6c  ...6........Hell
        0x0060:  6f2c 2077 6f72 6c64 2120 3533 0000 0000  o,.world!.53....
        0x0070:  0700 001c 0000 0000 0000 1303 0000 0000  ................
        0x0080:  0000 0036 0000 0000 0000 0036 0000 0002  ...6.......6....
```

**Comment by rotu** [comment]
Thank you! And thanks for providing such detailed troubleshooting info!!!

**Comment by rotu** [comment]
I still gotta figure out this CI stuff... Merging anyway.

**Comment by dodsonmg** [comment]
Any chance of getting this merged with `dashing-eloquent` branch?

**Pull request merged**
