### PR TITLE
rename rosidl_generator_c namespace to rosidl_runtime_c

### PR DESCRIPTION
**Pull request by dirk-thomas**
Related to ros2/rosidl#458.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The GitHub actions are expected to fail since they don't use the changes in the referenced PRs.

**Comment by rotu** [comment]
FYI: submitted https://github.com/ros-tooling/action-ros-ci/issues/157 to support testing these sorts of PRs.

**Comment by rotu** [comment]
LGTM once https://github.com/ros2/rosidl/pull/458 gets merged and CI passes.

**Comment by dirk-thomas** [comment]
@rotu Once the CI build in the referenced ticket passed the plan is to merge all PRs at once. Holding some PRs back until their custom actions pass (because they are not able to work for cross-repo changes) is not desired since during that time window the build of ROS 2 would be broken.

**Comment by rotu** [comment]
> @rotu Once the CI build in the referenced ticket passed the plan is to merge all PRs at once. Holding some PRs back until their custom actions pass (because they are not able to work for cross-repo changes) is not desired since during that time window the build of ROS 2 would be broken.

Once the CI in the referenced ticket passes, rerun this repo's CI. If there are no more commits on this branch and it passes CI, you can assume my approval. Github doesn't support "merging multiple PRs at once" - merging is an atomic operation in only one repo at a time and the point of CI is to reduce errors in this and other human operations.

**Pull request merged**
