### PR TITLE
compare string contents but string pointer addresses.

### PR DESCRIPTION
**Pull request by fujitatomoya**
address https://github.com/ros2/rmw_fastrtps/issues/742

### CODE REVIEW

**Review by fujitatomoya — COMMENTED** [review]
@eboasson can i have your review on this? originally related to https://github.com/ros2/rmw_fastrtps/issues/742, but it would be better to fix rmw_cyclonedds accordingly?

**Comment by clalancette** [comment]
FYI, this is a better version of #320 , which tried to fix the same thing for the same reason but just got held up.  I'm going to close that one and review this one.

**Review by clalancette — APPROVED** [review]
Looks reasonable to me with green CI.

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20390/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14801/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21140/)

**Comment by eboasson** [comment]
Sorry I'm so behind on things ... I am trying to catch up, please don't think I am don't care anymore!

I would've approved this one ☺️

**Comment by fujitatomoya** [comment]
@eboasson thanks for the comment. no worries, same here 😅

**Pull request merged**
