### PR TITLE
Fix format string incorrect use of %ld/%d instead of %zu/%PRIu32

### PR DESCRIPTION
**Pull request by eboasson**
This builds on #233 by also fixing the %d bit.

### CODE REVIEW

**Review by ivanpauno — APPROVED** [review]

**Comment by eboasson** [comment]
@clalancette oops, this time I forgot my own PR! Yes, it is still applicable, so we should try that.

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16731/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11313/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17126/)

**Comment by ivanpauno** [comment]
Failure on Windows seems unrelated.
@clalancette if you agree, I think we can merge this.

**Comment by clalancette** [comment]
Yeah, agreed.  Merging.

**Pull request merged**
